name: Publish to GH Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     platform: [linux/amd64, linux/arm64]

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        install_url: https://nixos.org/nix/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-substituters = https://viperml.cachix.org
          extra-trusted-public-keys = viperml.cachix.org-1:qZhKBMTfmcLL+OG6fj/hzsMEedgKvZVFRRAhq7j8Vh8=

    - name: Login to cachix
      uses: cachix/cachix-action@master
      with:
        name: viperml
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build image streamer
      run: nix build .#image-stream -L

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: .
    #     platforms: ${{ matrix.platform }}
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
    - name: Stream image to remote
      run: ./result | docker cp - ${{ steps.meta.outputs.tags }}
